In [51]:
import pandas as pd
import random

macbeth_df = pd.read_fwf('macbeth.txt')
macbeth_df.columns = ['text']

In [52]:
macbeth_df

                                                   text
0                                THE TRAGEDY OF MACBETH
1                                by William Shakespeare
2                                     Dramatis Personae
3                              DUNCAN, King of Scotland
4     MACBETH, Thane of Glamis and Cawdor, a general...
...                                                 ...
2660       We will perform in measure, time, and place.
2661          So thanks to all at once and to each one,
2662         Whom we invite to see us crown'd at Scone.
2663                                  Flourish. Exeunt.
2664                                          -THE END-

[2665 rows x 1 columns]

In [53]:
import numpy as np

splits = np.array_split(macbeth_df, 5)

# Split 0 -> Caesar Cipher

In [54]:
def caesar_encrypt(text, s=7):
    result = ""
    # transverse the plain text
    for i in range(len(text)):
        char = text[i]
        # Encrypt uppercase characters in plain text
        
        if (char.isupper()):
            result += chr((ord(char) + s-65) % 26 + 65)
        # Encrypt lowercase characters in plain text
        else:
            result += chr((ord(char) + s - 97) % 26 + 97)
    return result

In [55]:
caesar_df = pd.DataFrame(columns=['algorithm', 'encrypt'])
caesar_df['encrypt'] = [caesar_encrypt(text, random.randint(0, 26)) for text in splits[0].text.values] 
caesar_df['algorithm'] = 'caesar'

In [56]:
caesar_df

    algorithm                                            encrypt
0      caesar                             RFClRPYECBWlMDlKYAZCRF
1      caesar                             speNzcczrdeJyrbvjgvriv
2      caesar                                  BpykyrgqlNcpqmlyc
3      caesar                           BSLAYLxlIglelmdlQamrjylb
4      caesar  GUWVYNBthNbuhyhizhAfugcmhuhxhWuqxilthuhayhyluf...
..        ...                                                ...
528    caesar     Ugrflfgqlqspacyqcxlqsaacqqmlrfyrlzsrlrfgqlzjmu
529    caesar         Jfdeqkybkqebkybxxiikxkakqebkbkaxxiikxebobw
530    caesar        Pihbvsfsnbidcbbhvwgbpobybobrbgvcozbctbhwasn
531    caesar    MukbtdzkcfdjxudbyvudjedsecurdRkjdyddjxuiudsqiui
532    caesar    Dluzapssuohcluqbknltluauolylguaohaudluibaualhjo

[533 rows x 2 columns]

# Split 1 -> Affine Cipher

## Code for Affine Cipher

In [57]:
class Affine(object):
    def __init__(self):
        pass

    def egcd(self, a, b): 
        x,y, u,v = 0,1, 1,0
        while a != 0: 
            q, r = b//a, b%a 
            m, n = x-u*q, y-v*q 
            b,a, x,y, u,v = a,r, u,v, m,n 
        gcd = b 
        return gcd, x, y 

    def modinv(self, a, m): 
        gcd, x, y = self.egcd(a, m) 
        if gcd != 1: 
            return None # modular inverse does not exist 
        else: 
            return x % m 
    
    def encrypt(self, text, key): 
        #E = (a*x + b) % 26 
        return ''.join([ chr(((key[0]*(ord(t) - ord('A')) + key[1] ) % 26) + ord('A')) for t in text.upper().replace(' ', '') ]) 


    def decrypt(self, cipher, key): 
        #D(E) = (a^-1 * (E - b)) % 26
        return ''.join([ chr(((self.modinv(key[0], 26)*(ord(c) - ord('A') - key[1])) % 26) + ord('A')) for c in cipher ]) 
      
affine = Affine()

In [58]:
affine_df = pd.DataFrame(columns=['algorithm', 'encrypt'])
affine_df['encrypt'] = [affine.encrypt(text, (random.randint(0, 26), random.randint(0, 26))) for text in splits[1].text.values]
affine_df['algorithm'] = 'affine'

In [59]:
affine_df

    algorithm                                            encrypt
0      affine          AUAAEUOYIKGMCKOAYIIQMOCMAGOYKKYMKMKGGKMGY
1      affine         FLPZHFJXFJXNHNXHFLXJFJNBXNXHFJHHTXTRJBFNPX
2      affine         PVHHDBJXRLDFBRDDJFDBRXVXVLDPVFXVBBJPLBNFPD
3      affine                UAAYMAGWOCEQYYMWQYMMMCWIAYAOMUMYQUU
4      affine                EYGECEOEYOQAYEUYOEQOOOOIAYEEAMWGKCE
..        ...                                                ...
528    affine      ZIVGODQHCGIODHUTQDXBHMQVIDORXAGRVABCRIXOVCGIX
529    affine  CEIIYYCQGKKKSCYESQEQUYACEIIYYCQGKAQWUYQESUQEGQ...
530    affine  TFFJJDFHVBHDVBFHFTTPFRPXBZPBRHJNFPFTPFNFNPFFTV...
531    affine                                     NNNNNNNNNNNNNN
532    affine                                  GVAANTSMSNOPQPBNS

[533 rows x 2 columns]

# Exporting to CSV

In [60]:
def export_df(df, filename):
    df.to_csv(filename, index=False)

# combine all the dataframes
combined_df = pd.concat([caesar_df, affine_df])

# export the combined dataframe
export_df(combined_df, 'dataset.csv')