In [49]:
import pandas as pd
import random

macbeth_df = pd.read_fwf('macbeth.txt')
macbeth_df.columns = ['text']

In [50]:
macbeth_df

                                                   text
0                                THE TRAGEDY OF MACBETH
1                                by William Shakespeare
2                                     Dramatis Personae
3                              DUNCAN, King of Scotland
4     MACBETH, Thane of Glamis and Cawdor, a general...
...                                                 ...
2660       We will perform in measure, time, and place.
2661          So thanks to all at once and to each one,
2662         Whom we invite to see us crown'd at Scone.
2663                                  Flourish. Exeunt.
2664                                          -THE END-

[2665 rows x 1 columns]

In [51]:
import numpy as np

splits = np.array_split(macbeth_df, 5)

# Split 0 -> Caesar Cipher

In [52]:
def caesar_encrypt(text, s=7):
    result = ""
    # transverse the plain text
    for i in range(len(text)):
        char = text[i]
        # Encrypt uppercase characters in plain text
        
        if (char.isupper()):
            result += chr((ord(char) + s-65) % 26 + 65)
        # Encrypt lowercase characters in plain text
        else:
            result += chr((ord(char) + s - 97) % 26 + 97)
    return result

In [53]:
caesar_df = pd.DataFrame(columns=['algorithm', 'encrypt'])
caesar_df['encrypt'] = [caesar_encrypt(text, random.randint(0, 26)) for text in splits[0].text.values] 
caesar_df['algorithm'] = 'caesar'

In [54]:
caesar_df

    algorithm                                            encrypt
0      caesar                             GURaGENTRQLaBSaZNPORGU
1      caesar                             lixGsvvskwxCrkuoczokbo
2      caesar                                  XluguncmhJylmihuy
3      caesar                           NEXMKXjxUsxqxypxCmydvkxn
4      caesar  NBDCFUIaoUibofopgoHmbnjtoboeoDbxepsaobohfofsbm...
..        ...                                                ...
528    caesar     Withnhisnsurceaseznsuccessonthatnbutnthisnblow
529    caesar         Iecdpjxajpdajxawwhhjwjzjpdajajzwwhhjwdanav
530    caesar        Rkjdxuhupdkfeddjxyidrqdadqdtdixeqbdevdjycup
531    caesar    PxnewgcnfigmaxgebyxgmhgvhfxugUnmgbggmaxlxgvtlxl
532    caesar    Fnwbcruuwqjenwsdmpnvnwcwqnaniwcqjcwfnwkdcwcnjlq

[533 rows x 2 columns]

# Split 1 -> Affine Cipher

## Code for Affine Cipher

In [55]:
class Affine(object):
    def __init__(self):
        pass

    def egcd(self, a, b): 
        x,y, u,v = 0,1, 1,0
        while a != 0: 
            q, r = b//a, b%a 
            m, n = x-u*q, y-v*q 
            b,a, x,y, u,v = a,r, u,v, m,n 
        gcd = b 
        return gcd, x, y 

    def modinv(self, a, m): 
        gcd, x, y = self.egcd(a, m) 
        if gcd != 1: 
            return None # modular inverse does not exist 
        else: 
            return x % m 
    
    def encrypt(self, text, key): 
        #E = (a*x + b) % 26 
        return ''.join([ chr(((key[0]*(ord(t) - ord('A')) + key[1] ) % 26) + ord('A')) for t in text.upper().replace(' ', '') ]) 


    def decrypt(self, cipher, key): 
        #D(E) = (a^-1 * (E - b)) % 26
        return ''.join([ chr(((self.modinv(key[0], 26)*(ord(c) - ord('A') - key[1])) % 26) + ord('A')) for c in cipher ]) 
      
affine = Affine()

In [56]:
affine_df = pd.DataFrame(columns=['algorithm', 'encrypt'])
affine_df['encrypt'] = [affine.encrypt(text, (random.randint(0, 26), random.randint(0, 26))) for text in splits[1].text.values]
affine_df['algorithm'] = 'affine'

In [57]:
affine_df

    algorithm                                            encrypt
0      affine          RVRRXVZBDTNJHTZRBDDPJZHJRNZBTTBJTJTNNTJNB
1      affine         OKQSEOUCOUCAEACEOKCUOUAICACEOUEEWCWGUIOAQC
2      affine         TLVVJQORMUJPQZWJOPJQMRLELHWGLPRLQDOTUDAPTJ
3      affine                EDDZODPISHYJMMBVJMBOBHIGDZQSBEOZJEE
4      affine                ICKIGISICSUECIYCSIUSSSSMECIIEQAKOGI
..        ...                                                ...
528    affine      EHUPJOBYFPHJOYLCBOMWYRBUHOJKMNPKUNWFKHMJUFPHM
529    affine  IYEECPIQOHHUTVPYTQLQJCFIYEECPIQOHFQMJPQLGJQYBQ...
530    affine  NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...
531    affine                                     DZENNNCTZVQVNC
532    affine                                  BUJJWOLTLWZCFCMWL

[533 rows x 2 columns]

# Step 5: Railfence Cipher

In [58]:
class RailFence(object):
    def __init__(self):
        pass

    def matrix(self, text, key): 
        try:
            rail = [['\n' for i in range(len(text))] for j in range(key)]
            dir_down = False
            row, col = 0, 0

            for i in range(len(text)):
                if (row == 0) or (row == key - 1):
                    dir_down = not dir_down
                rail[row][col] = text[i]
                col += 1
                if dir_down:
                    row += 1
                else:
                    row -= 1
        except:
            print("ERROR", text, key)

        return rail
    
    def encrypt(self, text, key): 

        rail=self.matrix(text,key)
        result = []
        for i in range(key):
            for j in range(len(text)):
                if rail[i][j] != '\n':
                    result.append(rail[i][j])
        return("" . join(result))

        
rail_fence = RailFence()

In [59]:
rail_fence_df = pd.DataFrame(columns=['algorithm', 'encrypt'])
rail_fence_df['encrypt'] = [rail_fence.encrypt(text, random.randint(2, len(text))) for text in splits[2].text.values]
rail_fence_df['algorithm'] = 'rail_fence'

In [60]:
rail_fence_df

      algorithm                                            encrypt
0    rail_fence                                      E.notueqrn aB
1    rail_fence  BanaAhsiglmN tK,GiQu    sUoi:C,,Ohtwar ,.T owo...
2    rail_fence            A s,a dntedhs eiI m wofereipar rdn ewmo
3    rail_fence   T htioetuy   wp;altsa' yrs'oadfis dty lmlousotf
4    rail_fence              It should not, ysttiarnedt sionp  tyh
..          ...                                                ...
528  rail_fence                Hath so exaspereaht et athhte  gKni
529  rail_fence                  Prepares for some attem.prta wo f
530  rail_fence                        LENNOX. Sen?tf fhued ctaoM
531  rail_fence   LSO"iR rDe,.t  unHloeot s dbIia,d ",n aa nhdt iw
532  rail_fence            The cloudy ,mkecsasbe nsgiehr  etmu rsn

[533 rows x 2 columns]

# Exporting to CSV

In [61]:
def export_df(df, filename):
    df.to_csv(filename, index=False)

# combine all the dataframes
combined_df = pd.concat([caesar_df, affine_df, rail_fence_df])

# export the combined dataframe
export_df(combined_df, 'dataset.csv')